import mongoose from "mongoose";
import Medicine from "../models/medicine-model.js";
import dotenv from "dotenv";

const medicines = [
  {
    name: "Aspirin",
    type: "Pain Reliever",
    dosage: "325mg",
    description:
      "Used for pain relief, fever reduction, and cardiovascular protection.",
    uses: [
      "Pain relief",
      "Fever reduction",
      "Anti-inflammatory",
      "Heart protection",
    ],
    sideEffects: ["Stomach upset", "Nausea", "Dizziness", "Bleeding risk"],
    precautions: [
      "Take with food",
      "Avoid if allergic to NSAIDs",
      "Consult doctor for long-term use",
    ],
    price: "₹90",
  },
  {
    name: "Ibuprofen",
    type: "NSAID",
    dosage: "200mg",
    description: "Reduces inflammation, pain, and fever.",
    uses: ["Pain relief", "Fever control", "Inflammation", "Muscle aches"],
    sideEffects: ["Stomach pain", "Heartburn", "Drowsiness", "Kidney issues"],
    precautions: ["Take with food", "Avoid alcohol", "Monitor kidney function"],
    price: "₹35",
  },
  {
    name: "Paracetamol",
    type: "Analgesic",
    dosage: "500mg",
    description: "Common medication for mild to moderate pain and fever.",
    uses: ["Fever", "Mild pain", "Cold symptoms", "Headaches"],
    sideEffects: ["Liver damage (overdose)", "Allergic reaction", "Rash"],
    precautions: [
      "Do not exceed dose",
      "Avoid alcohol",
      "Monitor liver function",
    ],
    price: "₹12",
  },
  {
    name: "Amoxicillin",
    type: "Antibiotic",
    dosage: "500mg",
    description: "Broad-spectrum antibiotic used for bacterial infections.",
    uses: [
      "Throat infection",
      "UTI",
      "Respiratory infection",
      "Dental infections",
    ],
    sideEffects: ["Nausea", "Diarrhea", "Rash", "Yeast infection"],
    precautions: [
      "Finish the course",
      "Take with meals",
      "Avoid if allergic to penicillin",
    ],
    price: "₹65",
  },
  {
    name: "Omeprazole",
    type: "PPI",
    dosage: "20mg",
    description: "Reduces stomach acid and treats GERD.",
    uses: ["Acid reflux", "Heartburn", "Gastritis", "Stomach ulcers"],
    sideEffects: ["Headache", "Constipation", "Bloating", "B12 deficiency"],
    precautions: [
      "Take before meals",
      "Avoid long-term use",
      "Consult doctor if symptoms persist",
    ],
    price: "₹45",
  },
  {
    name: "Metformin",
    type: "Antidiabetic",
    dosage: "500mg",
    description: "Used to control blood sugar in type 2 diabetes.",
    uses: ["Type 2 diabetes", "PCOS", "Prediabetes", "Insulin resistance"],
    sideEffects: [
      "Nausea",
      "Metallic taste",
      "Diarrhea",
      "Lactic acidosis (rare)",
    ],
    precautions: [
      "Take with meals",
      "Monitor kidney function",
      "Avoid alcohol",
    ],
    price: "₹25",
  },
  {
    name: "Cetirizine",
    type: "Antihistamine",
    dosage: "10mg",
    description: "Treats allergies and cold symptoms.",
    uses: ["Sneezing", "Itchy eyes", "Runny nose", "Allergic rhinitis"],
    sideEffects: ["Drowsiness", "Dry mouth", "Headache", "Fatigue"],
    precautions: ["Avoid driving", "Limit alcohol", "Take at night if drowsy"],
    price: "₹20",
  },
  {
    name: "Azithromycin",
    type: "Antibiotic",
    dosage: "250mg",
    description: "Used to treat respiratory and bacterial infections.",
    uses: ["Throat infection", "Sinusitis", "Skin infection", "UTI"],
    sideEffects: [
      "Diarrhea",
      "Nausea",
      "Abdominal pain",
      "Liver enzymes elevated",
    ],
    precautions: ["Complete dose", "Avoid antacids", "Consult if allergic"],
    price: "₹60",
  },
  {
    name: "Loratadine",
    type: "Antihistamine",
    dosage: "10mg",
    description: "Non-drowsy medication for allergies.",
    uses: ["Hay fever", "Allergic rhinitis", "Hives", "Itchy skin"],
    sideEffects: ["Headache", "Nervousness", "Dry mouth", "Fatigue"],
    precautions: [
      "Avoid alcohol",
      "Inform doctor if pregnant",
      "Use once daily",
    ],
    price: "₹18",
  },
  {
    name: "Levothyroxine",
    type: "Hormone",
    dosage: "50mcg",
    description: "Synthetic thyroid hormone for hypothyroidism.",
    uses: ["Hypothyroidism", "Thyroid disorders", "Goiter"],
    sideEffects: ["Palpitations", "Insomnia", "Weight loss", "Anxiety"],
    precautions: [
      "Take on empty stomach",
      "Avoid calcium/iron near dose",
      "Monitor TSH levels",
    ],
    price: "₹55",
  },
  {
    name: "Ranitidine",
    type: "H2 Blocker",
    dosage: "150mg",
    description: "Used to reduce stomach acid.",
    uses: ["Acidity", "Ulcers", "GERD", "Heartburn"],
    sideEffects: ["Headache", "Constipation", "Fatigue", "Confusion (elderly)"],
    precautions: [
      "Avoid alcohol",
      "Take at night",
      "Consult if kidney disease",
    ],
    price: "₹30",
  },
  {
    name: "Doxycycline",
    type: "Antibiotic",
    dosage: "100mg",
    description: "Broad-spectrum antibiotic for infections and acne.",
    uses: ["Acne", "Malaria prophylaxis", "STDs", "Respiratory infection"],
    sideEffects: [
      "Sun sensitivity",
      "Nausea",
      "Vomiting",
      "Tooth discoloration",
    ],
    precautions: [
      "Avoid dairy",
      "Take with water",
      "Don’t lie down after dose",
    ],
    price: "₹70",
  },
  {
    name: "Pantoprazole",
    type: "PPI",
    dosage: "40mg",
    description: "Used to treat acid-related stomach issues.",
    uses: ["GERD", "Acid reflux", "Ulcers", "Stomach protection"],
    sideEffects: ["Headache", "Gas", "Diarrhea", "Joint pain"],
    precautions: ["Take before food", "Avoid NSAIDs", "Monitor calcium"],
    price: "₹45",
  },
  {
    name: "Clopidogrel",
    type: "Antiplatelet",
    dosage: "75mg",
    description: "Prevents blood clots in heart and brain patients.",
    uses: ["Stroke prevention", "Heart attack prevention", "Angina"],
    sideEffects: ["Bleeding", "Bruising", "Rash", "Diarrhea"],
    precautions: ["Avoid injury", "Report bleeding", "Don’t stop suddenly"],
    price: "₹90",
  },
  {
    name: "Losartan",
    type: "Antihypertensive",
    dosage: "50mg",
    description: "Used to manage high blood pressure and kidney issues.",
    uses: ["High BP", "Heart failure", "Diabetic kidney disease"],
    sideEffects: ["Dizziness", "Fatigue", "Low BP", "High potassium"],
    precautions: [
      "Monitor BP",
      "Avoid potassium supplements",
      "Don’t skip doses",
    ],
    price: "₹35",
  },
  {
    name: "Amlodipine",
    type: "Calcium Channel Blocker",
    dosage: "5mg",
    description: "Relaxes blood vessels to lower blood pressure.",
    uses: ["High BP", "Chest pain (angina)", "Heart failure"],
    sideEffects: ["Swelling", "Fatigue", "Palpitations", "Flushing"],
    precautions: [
      "Avoid grapefruit juice",
      "Check BP regularly",
      "Don’t miss dose",
    ],
    price: "₹30",
  },
  {
    name: "Atorvastatin",
    type: "Statin",
    dosage: "10mg",
    description: "Lowers cholesterol and reduces heart risk.",
    uses: ["High cholesterol", "Heart disease prevention", "Stroke prevention"],
    sideEffects: ["Muscle pain", "Liver issues", "Nausea", "Fatigue"],
    precautions: ["Avoid alcohol", "Regular liver tests", "Report muscle pain"],
    price: "₹50",
  },
  {
    name: "Insulin Glargine",
    type: "Insulin",
    dosage: "100IU/ml",
    description: "Long-acting insulin for diabetes control.",
    uses: ["Type 1 diabetes", "Type 2 diabetes"],
    sideEffects: ["Hypoglycemia", "Weight gain", "Injection site pain"],
    precautions: ["Monitor sugar", "Use consistently", "Avoid skipping meals"],
    price: "₹320",
  },
  {
    name: "Salbutamol",
    type: "Bronchodilator",
    dosage: "100mcg",
    description: "Relieves asthma and wheezing.",
    uses: ["Asthma", "COPD", "Bronchospasm"],
    sideEffects: [
      "Tremors",
      "Fast heartbeat",
      "Nervousness",
      "Throat irritation",
    ],
    precautions: ["Use spacer", "Don’t exceed dose", "Clean inhaler regularly"],
    price: "₹40",
  },
  {
    name: "Montelukast",
    type: "Leukotriene Receptor Antagonist",
    dosage: "10mg",
    description: "Used for asthma and allergic rhinitis.",
    uses: ["Asthma", "Allergies", "Nasal congestion"],
    sideEffects: ["Headache", "Dizziness", "Fatigue", "Mood changes"],
    precautions: ["Take at night", "Not for acute asthma", "Monitor mood"],
    price: "₹55",
  },
  {
    name: "Hydrochlorothiazide",
    type: "Diuretic",
    dosage: "25mg",
    description: "Reduces excess fluid and controls blood pressure.",
    uses: ["High BP", "Edema", "Heart failure"],
    sideEffects: ["Frequent urination", "Low potassium", "Dizziness"],
    precautions: [
      "Monitor electrolytes",
      "Avoid dehydration",
      "Check BP regularly",
    ],
    price: "₹28",
  },
  {
    name: "Prednisolone",
    type: "Corticosteroid",
    dosage: "10mg",
    description: "Treats inflammation, allergies, and autoimmune conditions.",
    uses: ["Asthma", "Arthritis", "Allergic reactions"],
    sideEffects: ["Weight gain", "Mood swings", "Increased appetite"],
    precautions: ["Don’t stop suddenly", "Monitor sugar", "Avoid infection"],
    price: "₹32",
  },
  {
    name: "Fluconazole",
    type: "Antifungal",
    dosage: "150mg",
    description: "Treats fungal and yeast infections.",
    uses: ["Vaginal candidiasis", "Oral thrush", "Skin infections"],
    sideEffects: ["Nausea", "Headache", "Stomach upset"],
    precautions: [
      "Take as prescribed",
      "Avoid alcohol",
      "Inform if liver issues",
    ],
    price: "₹20",
  },
  {
    name: "Zinc Sulfate",
    type: "Supplement",
    dosage: "50mg",
    description: "Boosts immunity and promotes wound healing.",
    uses: ["Zinc deficiency", "Diarrhea", "Wound healing"],
    sideEffects: ["Stomach upset", "Metallic taste", "Nausea"],
    precautions: ["Take after food", "Avoid overdose", "Consult if pregnant"],
    price: "₹12",
  },
  {
    name: "Folic Acid",
    type: "Vitamin",
    dosage: "5mg",
    description: "Supports red blood cell production and fetal development.",
    uses: ["Anemia", "Pregnancy", "Folic acid deficiency"],
    sideEffects: ["Nausea", "Bloating", "Bitter taste"],
    precautions: [
      "Continue during pregnancy",
      "Take with food",
      "Consult doctor",
    ],
    price: "₹8",
  },
  {
    name: "Calcium Carbonate",
    type: "Supplement",
    dosage: "500mg",
    description: "Supports bone health and treats calcium deficiency.",
    uses: ["Osteoporosis", "Calcium deficiency", "Pregnancy"],
    sideEffects: ["Constipation", "Gas", "Stomach upset"],
    precautions: ["Take after meals", "Avoid excess", "Monitor calcium levels"],
    price: "₹15",
  },
  {
    name: "Vitamin D3",
    type: "Supplement",
    dosage: "60,000 IU",
    description: "Essential for calcium absorption and bone health.",
    uses: ["Vitamin D deficiency", "Bone health", "Weakness"],
    sideEffects: ["Fatigue", "Headache", "Nausea"],
    precautions: ["Avoid overdose", "Take weekly", "Consult for long use"],
    price: "₹35",
  },
  {
    name: "Iron Folic Acid",
    type: "Supplement",
    dosage: "100mg",
    description: "Used to prevent and treat iron-deficiency anemia.",
    uses: ["Anemia", "Pregnancy", "Fatigue"],
    sideEffects: ["Constipation", "Dark stools", "Stomach upset"],
    precautions: ["Take after food", "Don’t overdose", "Use during pregnancy"],
    price: "₹10",
  },
  {
    name: "Ondansetron",
    type: "Antiemetic",
    dosage: "4mg",
    description: "Prevents nausea and vomiting due to various causes.",
    uses: ["Post-op nausea", "Chemotherapy-induced nausea", "Morning sickness"],
    sideEffects: ["Constipation", "Headache", "Dizziness"],
    precautions: ["Avoid driving", "Take before meals", "Monitor heart rhythm"],
    price: "₹25",
  },
  {
    name: "Spironolactone",
    type: "Diuretic",
    dosage: "25mg",
    description: "Treats fluid retention and hormonal acne.",
    uses: ["Heart failure", "Acne", "PCOS"],
    sideEffects: ["High potassium", "Breast tenderness", "Drowsiness"],
    precautions: [
      "Monitor potassium",
      "Avoid salt substitutes",
      "Check kidney function",
    ],
    price: "₹40",
  },
  {
    name: "Bisoprolol",
    type: "Beta-blocker",
    dosage: "5mg",
    description: "Used to treat high blood pressure and heart conditions.",
    uses: ["Hypertension", "Heart failure", "Angina"],
    sideEffects: ["Fatigue", "Cold hands", "Slow heartbeat"],
    precautions: ["Don’t stop suddenly", "Monitor BP", "Avoid alcohol"],
    price: "₹32",
  },
  {
    name: "Carbamazepine",
    type: "Anticonvulsant",
    dosage: "200mg",
    description: "Controls seizures and nerve pain.",
    uses: ["Epilepsy", "Trigeminal neuralgia", "Bipolar disorder"],
    sideEffects: ["Drowsiness", "Blurred vision", "Nausea"],
    precautions: ["Avoid alcohol", "Regular blood tests", "Take regularly"],
    price: "₹55",
  },
  {
    name: "Rabeprazole",
    type: "PPI",
    dosage: "20mg",
    description: "Reduces stomach acid and treats GI conditions.",
    uses: ["GERD", "Ulcers", "Acid reflux"],
    sideEffects: ["Headache", "Bloating", "Nausea"],
    precautions: [
      "Take before meals",
      "Avoid long-term use",
      "Consult if needed",
    ],
    price: "₹42",
  },
  {
    name: "Melatonin",
    type: "Hormone",
    dosage: "3mg",
    description: "Natural sleep aid used for sleep disorders.",
    uses: ["Insomnia", "Jet lag", "Shift work disorder"],
    sideEffects: ["Drowsiness", "Headache", "Dizziness"],
    precautions: ["Avoid driving", "Take at night", "Limit caffeine"],
    price: "₹30",
  },
  {
    name: "Loperamide",
    type: "Antidiarrheal",
    dosage: "2mg",
    description: "Used to reduce frequency of diarrhea.",
    uses: ["Acute diarrhea", "IBS", "Travelers’ diarrhea"],
    sideEffects: ["Constipation", "Nausea", "Dizziness"],
    precautions: [
      "Don’t exceed dose",
      "Hydrate well",
      "Stop if no relief in 2 days",
    ],
    price: "₹12",
  },
  {
    name: "Domperidone",
    type: "Prokinetic",
    dosage: "10mg",
    description: "Improves gastric motility and reduces nausea.",
    uses: ["Nausea", "Indigestion", "Bloating"],
    sideEffects: ["Dry mouth", "Headache", "Abdominal cramps"],
    precautions: [
      "Take before meals",
      "Avoid with certain antibiotics",
      "Limit use",
    ],
    price: "₹18",
  },
  {
    name: "Tamsulosin",
    type: "Alpha Blocker",
    dosage: "0.4mg",
    description: "Treats urinary symptoms from enlarged prostate.",
    uses: ["BPH", "Urine retention", "Prostate issues"],
    sideEffects: ["Dizziness", "Ejaculation problems", "Low BP"],
    precautions: ["Take at night", "Avoid alcohol", "Monitor BP"],
    price: "₹45",
  },
  {
    name: "Phenylephrine",
    type: "Decongestant",
    dosage: "10mg",
    description: "Relieves nasal and sinus congestion.",
    uses: ["Cold", "Sinusitis", "Nasal congestion"],
    sideEffects: ["Increased BP", "Insomnia", "Restlessness"],
    precautions: ["Avoid at night", "Check BP", "Don’t use long-term"],
    price: "₹16",
  },
  {
    name: "Budesonide Inhaler",
    type: "Corticosteroid",
    dosage: "200mcg",
    description: "Inhaled steroid for long-term asthma control.",
    uses: ["Asthma", "COPD"],
    sideEffects: ["Oral thrush", "Hoarseness", "Cough"],
    precautions: ["Rinse mouth after use", "Use regularly", "Avoid infection"],
    price: "₹220",
  },
  {
    name: "Olmesartan",
    type: "Antihypertensive",
    dosage: "20mg",
    description: "Controls high blood pressure.",
    uses: ["High BP", "Heart failure"],
    sideEffects: ["Dizziness", "Kidney issues", "Low BP"],
    precautions: ["Monitor BP", "Avoid in pregnancy", "Stay hydrated"],
    price: "₹38",
  },
  {
    name: "Chlorpheniramine",
    type: "Antihistamine",
    dosage: "4mg",
    description: "Relieves allergy symptoms and common cold.",
    uses: ["Runny nose", "Sneezing", "Itchy eyes", "Cold"],
    sideEffects: ["Drowsiness", "Dry mouth", "Dizziness"],
    precautions: ["Avoid alcohol", "Do not drive", "Take at night"],
    price: "₹14",
  },
  {
    name: "Acetylcysteine",
    type: "Mucolytic",
    dosage: "600mg",
    description: "Breaks down mucus in respiratory diseases.",
    uses: ["Cough", "Bronchitis", "COPD", "Paracetamol poisoning"],
    sideEffects: ["Nausea", "Vomiting", "Rash"],
    precautions: [
      "Take with water",
      "Consult doctor if asthmatic",
      "Do not exceed dose",
    ],
    price: "₹45",
  },
  {
    name: "Gliclazide",
    type: "Antidiabetic",
    dosage: "80mg",
    description: "Stimulates insulin secretion in type 2 diabetes.",
    uses: ["Type 2 diabetes"],
    sideEffects: ["Hypoglycemia", "Weight gain", "Nausea"],
    precautions: ["Take with food", "Monitor sugar", "Avoid skipping meals"],
    price: "₹28",
  },
  {
    name: "Sodium Bicarbonate",
    type: "Antacid",
    dosage: "500mg",
    description: "Neutralizes stomach acid and treats acidosis.",
    uses: ["Heartburn", "Acid indigestion", "Metabolic acidosis"],
    sideEffects: ["Gas", "Nausea", "Alkalosis"],
    precautions: ["Limit use", "Avoid with high BP", "Take after meals"],
    price: "₹10",
  },
  {
    name: "Dicyclomine",
    type: "Antispasmodic",
    dosage: "20mg",
    description: "Relieves abdominal cramps and spasms.",
    uses: ["IBS", "Stomach pain", "Cramps"],
    sideEffects: ["Dry mouth", "Blurred vision", "Constipation"],
    precautions: ["Avoid alcohol", "Do not drive", "Stay hydrated"],
    price: "₹22",
  },
  {
    name: "Sitagliptin",
    type: "Antidiabetic",
    dosage: "100mg",
    description: "Regulates insulin levels in type 2 diabetes.",
    uses: ["Type 2 diabetes"],
    sideEffects: ["Headache", "Sore throat", "Pancreatitis (rare)"],
    precautions: [
      "Monitor sugar",
      "Consult for kidney disease",
      "Avoid alcohol",
    ],
    price: "₹105",
  },
  {
    name: "Terbinafine",
    type: "Antifungal",
    dosage: "250mg",
    description: "Treats fungal infections of skin, hair, and nails.",
    uses: ["Ringworm", "Athlete’s foot", "Nail fungus"],
    sideEffects: ["Liver issues", "Rash", "Nausea"],
    precautions: ["Avoid alcohol", "Monitor liver", "Complete course"],
    price: "₹60",
  },
  {
    name: "Betahistine",
    type: "Anti-vertigo",
    dosage: "16mg",
    description: "Improves blood flow in inner ear for vertigo treatment.",
    uses: ["Vertigo", "Meniere’s disease"],
    sideEffects: ["Nausea", "Headache", "Bloating"],
    precautions: [
      "Take with food",
      "Avoid if gastric ulcers",
      "Use consistently",
    ],
    price: "₹40",
  },
  {
    name: "Naproxen",
    type: "NSAID",
    dosage: "250mg",
    description: "Reduces pain, swelling, and inflammation.",
    uses: ["Arthritis", "Muscle pain", "Menstrual cramps"],
    sideEffects: ["Stomach upset", "Heartburn", "Drowsiness"],
    precautions: ["Take with food", "Avoid long use", "Avoid alcohol"],
    price: "₹32",
  },
  {
    name: "Levocetirizine",
    type: "Antihistamine",
    dosage: "5mg",
    description: "Relieves allergy symptoms without causing much drowsiness.",
    uses: ["Allergies", "Runny nose", "Hives", "Sneezing"],
    sideEffects: ["Fatigue", "Dry mouth", "Headache"],
    precautions: ["Take at night", "Avoid alcohol", "Limit driving"],
    price: "₹20",
  },
  {
    name: "Ciprofloxacin",
    type: "Antibiotic",
    dosage: "500mg",
    description: "Treats bacterial infections.",
    uses: ["UTI", "GI infections", "Skin infections"],
    sideEffects: ["Nausea", "Dizziness", "Joint pain"],
    precautions: ["Avoid dairy", "Don’t use with antacids", "Complete course"],
    price: "₹38",
  },
  {
    name: "Rifampicin",
    type: "Antibiotic",
    dosage: "300mg",
    description: "Used in combination to treat tuberculosis.",
    uses: ["TB", "Leprosy", "Meningitis"],
    sideEffects: ["Orange urine", "Liver issues", "Flu symptoms"],
    precautions: ["Avoid alcohol", "Use with other TB drugs", "Monitor liver"],
    price: "₹85",
  },
  {
    name: "Clotrimazole Cream",
    type: "Antifungal",
    dosage: "1%",
    description: "Topical treatment for fungal skin infections.",
    uses: ["Ringworm", "Athlete’s foot", "Fungal rash"],
    sideEffects: ["Irritation", "Itching", "Redness"],
    precautions: [
      "Use externally only",
      "Clean area before use",
      "Apply thin layer",
    ],
    price: "₹25",
  },
  {
    name: "Isosorbide Mononitrate",
    type: "Vasodilator",
    dosage: "30mg",
    description: "Relieves chest pain by widening blood vessels.",
    uses: ["Angina", "Heart failure"],
    sideEffects: ["Dizziness", "Headache", "Low BP"],
    precautions: ["Do not crush", "Avoid sudden standing", "Avoid alcohol"],
    price: "₹60",
  },
  {
    name: "Phenytoin",
    type: "Antiepileptic",
    dosage: "100mg",
    description: "Controls seizures and convulsions.",
    uses: ["Epilepsy", "Seizure disorders"],
    sideEffects: ["Gum swelling", "Drowsiness", "Nausea"],
    precautions: [
      "Maintain oral hygiene",
      "Regular blood tests",
      "Avoid alcohol",
    ],
    price: "₹36",
  },
  {
    name: "Lansoprazole",
    type: "PPI",
    dosage: "30mg",
    description: "Reduces stomach acid and heals ulcers.",
    uses: ["GERD", "Ulcers", "Heartburn"],
    sideEffects: ["Diarrhea", "Abdominal pain", "Gas"],
    precautions: [
      "Take before meals",
      "Avoid long-term use",
      "Consult if needed",
    ],
    price: "₹42",
  },
  {
    name: "Cefixime",
    type: "Antibiotic",
    dosage: "200mg",
    description:
      "Treats bacterial infections including throat and urinary infections.",
    uses: ["Throat infection", "UTI", "Sinusitis"],
    sideEffects: ["Diarrhea", "Rash", "Abdominal pain"],
    precautions: ["Complete course", "Take after food", "Avoid skipping dose"],
    price: "₹50",
  },
  {
    name: "Tizanidine",
    type: "Muscle Relaxant",
    dosage: "2mg",
    description: "Relieves muscle spasms and tightness.",
    uses: ["Muscle spasm", "Spasticity", "Back pain"],
    sideEffects: ["Drowsiness", "Dry mouth", "Low BP"],
    precautions: ["Avoid alcohol", "Take at bedtime", "Don’t drive"],
    price: "₹28",
  },
  {
    name: "Miconazole",
    type: "Antifungal",
    dosage: "2%",
    description: "Topical antifungal for skin and oral infections.",
    uses: ["Oral thrush", "Fungal rash", "Ringworm"],
    sideEffects: ["Burning", "Redness", "Irritation"],
    precautions: ["Use externally", "Avoid eyes", "Clean area before use"],
    price: "₹18",
  },
  {
    name: "Nitrofurantoin",
    type: "Antibiotic",
    dosage: "100mg",
    description: "Treats uncomplicated urinary tract infections.",
    uses: ["UTI"],
    sideEffects: ["Nausea", "Headache", "Dark urine"],
    precautions: [
      "Take with food",
      "Complete full course",
      "Avoid in kidney issues",
    ],
    price: "₹38",
  },
  {
    name: "Hydroxyzine",
    type: "Antihistamine",
    dosage: "25mg",
    description: "Relieves anxiety, nausea, and allergies.",
    uses: ["Anxiety", "Nausea", "Itching", "Insomnia"],
    sideEffects: ["Drowsiness", "Dry mouth", "Dizziness"],
    precautions: ["Avoid alcohol", "Do not drive", "Take at bedtime"],
    price: "₹33",
  },
  {
    name: "Methotrexate",
    type: "Immunosuppressant",
    dosage: "10mg",
    description: "Used to treat autoimmune diseases and cancers.",
    uses: ["Rheumatoid arthritis", "Psoriasis", "Cancer"],
    sideEffects: ["Mouth ulcers", "Liver toxicity", "Fatigue"],
    precautions: ["Weekly dose", "Regular blood tests", "Avoid alcohol"],
    price: "₹80",
  },
  {
    name: "Sucralfate",
    type: "GI Protectant",
    dosage: "1g",
    description: "Forms a coating on ulcers to protect from acid.",
    uses: ["Ulcers", "GERD"],
    sideEffects: ["Constipation", "Dry mouth", "Gas"],
    precautions: [
      "Take on empty stomach",
      "Avoid antacids",
      "Take separately from other meds",
    ],
    price: "₹27",
  },
  {
    name: "Erythromycin",
    type: "Antibiotic",
    dosage: "250mg",
    description: "Used to treat various bacterial infections.",
    uses: ["Throat infection", "Acne", "Eye infections"],
    sideEffects: ["Nausea", "Stomach upset", "Diarrhea"],
    precautions: ["Take after food", "Complete dose", "Avoid if liver disease"],
    price: "₹35",
  },
  {
    name: "Risperidone",
    type: "Antipsychotic",
    dosage: "2mg",
    description: "Treats schizophrenia and bipolar disorder.",
    uses: ["Schizophrenia", "Bipolar disorder", "Irritability in autism"],
    sideEffects: ["Weight gain", "Sleepiness", "Tremor"],
    precautions: [
      "Take regularly",
      "Avoid alcohol",
      "Consult for side effects",
    ],
    price: "₹65",
  },
  {
    name: "Amikacin",
    type: "Antibiotic (Injection)",
    dosage: "500mg",
    description: "Strong antibiotic for severe bacterial infections.",
    uses: ["Sepsis", "Infections resistant to other antibiotics"],
    sideEffects: ["Kidney damage", "Hearing loss", "Injection site pain"],
    precautions: [
      "Monitor kidney function",
      "Hydrate well",
      "Hospital use only",
    ],
    price: "₹90",
  },
  {
    name: "Metoclopramide",
    type: "Prokinetic",
    dosage: "10mg",
    description: "Used to treat nausea, vomiting, and slow stomach emptying.",
    uses: ["GERD", "Gastroparesis", "Nausea"],
    sideEffects: ["Drowsiness", "Restlessness", "Diarrhea"],
    precautions: ["Avoid long-term use", "Take before meals", "Avoid alcohol"],
    price: "₹16",
  },
];

async function SeedData() {
  await mongoose
    .connect("mongodb://localhost:27017/medicore", {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    })
    .then(async () => {
      await Medicine.deleteMany();
      await Medicine.insertMany(medicines);
      mongoose.disconnect();
    })
    .catch((err) => {
      // console.error(err); // Removed console.error
    });
}

SeedData();
